apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-custom-config-list
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  whitelist.txt: |
    0.client-channel.google.com
    0-edge-chat.facebook.com
    1drv.com
    1-edge-chat.facebook.com
    2.android.pool.ntp.org
    2-edge-chat.facebook.com
    3-edge-chat.facebook.com
    4-edge-chat.facebook.com
    5-edge-chat.facebook.com
    6-edge-chat.facebook.com
    7eer.net
    a463.w10.akamai.net
    a790.w16.akamai.net
    acdn.adnxs.com
    ad.doubleclick.net
    adf.ly
    ae01.alicdn.com
    affiliatefuture.com
    akamaihd.net
    akamaitechnologies.com
    akamaized.net
    alluremedia.com.au
    amazonaws.com
    amd.cdn.turner.com
    android.clients.google.com
    anrdoezrs.net
    api.ipify.org
    api.pluto.tv
    api.sbs.com.au
    apmebf.com
    app-api.ted.com
    appleid.apple.com
    app.plex.tv
    appsbackup-pa.clients6.google.com
    appsbackup-pa.googleapis.com
    apps.skype.com
    apt.sonarr.tv
    aspnetcdn.com
    assets.adobedtm.com
    attestation.xboxlive.com
    avantlink.com
    ax.phobos.apple.com.edgesuite.net
    bfast.com
    bing.com
    bit.ly
    brightcove.net
    bufferapp.com
    cc-dt.com
    cdn1.smartadserver.com
    cdn2.optimizely.com
    cdn3.optimizely.com
    cdn.cloudflare.net
    cdn.embedly.com
    cdn.fbsbx.com
    cdnjs.cloudflare.com
    cdn-mobile.api.pluto.tv
    cdn.optimizely.com
    cdns.gigya.com
    cdn.vidible.tv
    cert.mgt.xboxlive.com
    cj.com
    cj.dotomi.com
    clickserve.cc-dt.com
    clientconfig.passport.net
    clients1.google.com
    clients2.google.com
    clients3.google.com
    clients4.google.com
    clients5.google.com
    clients6.google.com
    commission-junction.com
    cpms35.spop10.ams.plex.bz
    cpms.spop10.ams.plex.bz
    creative.ak.fbcdn.net
    crisp.chat
    cse.google.com
    c.s-microsoft.com
    ctldl.windowsupdate.com
    cwtv-mrss-akamai.cwtv.com
    cwtv-prod-elb.digitalsmiths.net
    d2c8v52ll5s99u.cloudfront.net
    d2gatte9o95jao.cloudfront.net
    dashboard.plex.tv
    dataplicity.com
    dcs-vod.apis.anvato.net
    def-vef.xboxlive.com
    delivery.vidible.tv
    device.auth.xboxlive.com
    device-metrics-us-2.amazon.com
    device-metrics-us.amazon.com
    dev.virtualearth.net
    directvapplications.hb.omtrdc.net
    directvnow.com
    displaycatalog.mp.microsoft.com
    display.ugc.bazaarvoice.com
    dl.delivery.mp.microsoft.com
    dl.dropbox.com
    dl.dropboxusercontent.com
    dns.msftncsi.com
    doubleclick.net
    download.sonarr.tv
    dpbolvw.net
    drift.com
    driftt.com
    dsms0mj1bbhn4.cloudfront.net
    dynupdate.no-ip.com
    e7065.e2.akamaiedge.net
    ecn.dev.virtualearth.net
    ec-ns.sascdn.com
    edge.api.brightcove.com
    edge-chat.facebook.com
    edge-mqtt.facebook.com
    eds.xboxlive.com
    emjcd.com
    entitlement.auth.adobe.com
    events.gfe.nvidia.com
    evyy.net
    external-lhr0-1.xx.fbcdn.net
    external-lhr10-1.xx.fbcdn.net
    external-lhr1-1.xx.fbcdn.net
    external-lhr2-1.xx.fbcdn.net
    external-lhr3-1.xx.fbcdn.net
    external-lhr4-1.xx.fbcdn.net
    external-lhr5-1.xx.fbcdn.net
    external-lhr6-1.xx.fbcdn.net
    external-lhr7-1.xx.fbcdn.net
    external-lhr8-1.xx.fbcdn.net
    external-lhr9-1.xx.fbcdn.net
    f1.media.brightcove.com
    facebook.com
    facebook.net
    fbcdn-creative-a.akamaihd.net
    fbcdn.net
    feeds.feedburner.com
    filament.io
    fonts.gstatic.com
    forums.sonarr.tv
    fpdownload.adobe.com
    gan.doubleclick.net
    geo3.ggpht.com
    geo-prod.do.dsp.mp.microsoft.com
    gfwsl.geforce.com
    giphy.com
    github.com
    github.io
    g.live.com
    go2jump.org
    goo.gl
    google-analytics.com
    googleapis.com
    gopjn.com
    go.redirectingat.com
    graph.facebook.com
    gravatar.com
    gstatic.com
    help.ui.xboxlive.com
    hls.ted.com
    hostsfile.mine.nu
    hosts-file.net
    hostsfile.org
    i1.ytimg.com
    i.cdn.turner.com
    icloud.com
    imagesak.secureserver.net
    images.pluto.tv
    imgix.net
    imgs.xkcd.com
    img.vidible.tv
    instantmessaging-pa.googleapis.com
    intercom.io
    i.s-microsoft.com
    i.ytimg.com
    jdoqocy.com
    j.mp
    jquery.com
    jsdelivr.net
    js.maxmind.com
    keystone.mwbsys.com
    kqzyfj.com
    lastfm-img2.akamaized.net
    licensing.xboxlive.com
    linkedin.com
    linksynergy.com
    link.theplatform.com
    linuxtracker.org
    live.com
    livepassdl.conviva.com
    login.aliexpress.com
    login.live.com
    login.microsoftonline.com
    lotustalk.com
    manifest.auditude.com
    manifest.googlevideo.com
    media.sbs.com.au
    meta-db-worker02.pop.ric.plex.bz
    meta.plex.bz
    meta.plex.tv
    m.hotmail.com
    microsoft.com
    microsoftonline.com
    msftncsi.com
    m.weeklyad.target.com
    my.plexapp.com
    nexusrules.officeapps.live.com
    nine.plugins.plexapp.com
    node.plexapp.com
    no-ip.com
    notify.xboxlive.com
    ns1.dropbox.com
    ns2.dropbox.com
    o1.email.plex.tv
    o2.sg0.plex.tv
    ocsp.apple.com
    office365.com
    officeclient.microsoft.com
    office.com
    office.net
    ojrq.net
    om.cbsi.com
    onedrive.live.com
    onenetworkdirect.net
    ota-downloads.nvidia.com
    outlook.live.com
    outlook.office365.com
    ow.ly
    pgl.yoyo.org
    pinterest.com
    pixel.nymag.com
    pjatr.com
    pjtra.com
    placehold.it
    placeholdit.imgix.net
    players.brightcove.net
    players.pluto.tv
    plex.tv
    pmd.cdn.turner.com
    pntrac.com
    pntrack.com
    pntra.com
    pricelist.skype.com
    prod.telemetry.ros.rockstargames.com
    products.office.com
    proxy02.pop.ord.plex.bz
    proxy.plex.bz
    proxy.plex.tv
    pubsub.plex.bz
    pubsub.plex.tv
    qksrv.net
    raw.githubusercontent.com
    reddit.com
    redirect.at
    redirectingat.com
    redirector.googlevideo.com
    redirect.viglink.com
    res.cloudinary.com
    resources.sbs.com.au
    s1.wp.com
    s2.youtube.com
    s3.amazonaws.com
    sa.symcb.com
    sbs.com.au
    sbsvodns-vh.akamaihd.net
    s.cdn.turner.com
    scontent.fgdl5-1.fna.fbcdn.net
    scontent-lhr3-1.xx.fbcdn.net
    scontent.xx.fbcdn.net
    secure.avangate.com
    secure.brightcove.com
    secure.surveymonkey.com
    services.sonarr.tv
    s.gateway.messenger.live.com
    shareaholic.com
    shareasale.com
    sharepoint.com
    siloh.pluto.tv
    silo.pluto.tv
    skyhook.sonarr.tv
    skype.com
    s.marketwatch.com
    someonewhocares.org
    spclient.wg.spotify.com
    sqs.us-east-1.amazonaws.com
    s.shopify.com
    ssl.google-analytics.com
    ssl.p.jwpcdn.com
    staging.plex.tv
    status.plex.tv
    stitcher.pluto.tv
    support.microsoft.com
    surveymonkey.com
    synology.com
    s.youtube.com
    sysctl.org
    s.ytimg.com
    s.zkcdn.net
    t0.ssl.ak.dynamic.tiles.virtualearth.net
    t0.ssl.ak.tiles.virtualearth.net
    tawk.to
    t.co
    tedcdn.com
    themoviedb.com
    thetvdb.com
    time.samsungcloudsolution.com
    tinyurl.com
    title.auth.xboxlive.com
    title.mgt.xboxlive.com
    tkqlhce.com
    track.ucas.com
    tradetracker.net
    tvdb2.plex.tv
    tvthemes.plexapp.com
    twimg.com
    twitter.com
    ui.skype.com
    unsplash.com
    v.firebog.net
    videocdn-sbs.akamaized.net
    video-stats.l.google.com
    videos.vidible.tv
    vimeo.com
    v.shopify.com
    weeklyad.target.com
    weeklyad.target.com.edgesuite.net
    widget-cdn.rpxnow.com
    wikipedia.org
    win10.ipv6.microsoft.com
    winhelp2002.mvps.org
    wordpress.com
    wp.com
    ws.audioscrobbler.com
    www.7eer.net
    www.adf.ly
    www.affiliatefuture.com
    www.anrdoezrs.net
    www.apmebf.com
    www.avantlink.com
    www.bfast.com
    www.bit.ly
    www.cc-dt.com
    www.cj.com
    www.dataplicity.com
    www.doubleclick.net
    www.dpbolvw.net
    www.emjcd.com
    www.evyy.net
    www.google-analytics.com
    www.googleapis.com
    www.gopjn.com
    www.icloud.com
    www.jdoqocy.com
    www.kqzyfj.com
    www.linksynergy.com
    www.linuxtracker.org
    www.lotustalk.com
    www.msftncsi.com
    www.no-ip.com
    www.ojrq.net
    www.onenetworkdirect.net
    www.ow.ly
    www.pjatr.com
    www.pjtra.com
    www.plex.tv
    www.pntrac.com
    www.pntrack.com
    www.pntra.com
    www.qksrv.net
    www.sbs.com.au
    www.solaredge.com
    www.synology.com
    www.tkqlhce.com
    www.tradetracker.net
    www.twitter.com
    www.xboxlive.com
    www.youtube-nocookie.com
    xboxexperiencesprod.experimentation.xboxlive.com
    xbox.ipv6.microsoft.com
    xflight.xboxlive.com
    xkms.xboxlive.com
    xsts.auth.xboxlive.com
    yahoo.com
    youtu.be
    youtube.com
    youtube-nocookie.com
    yt3.ggpht.com
    z.cdn.turner.com
    zeustracker.abuse.ch
  adlists.list: |
    https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 
    https://mirror1.malwaredomains.com/files/justdomains 
    http://sysctl.org/cameleon/hosts 
    https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist 
    https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt 
    https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt 
    https://hosts-file.net/ad_servers.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/HOSTS.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Ads-tracker.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/coinminer.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/Malware.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/filters/nsablocklist.txt 
    https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/uMatrix/CK's-uMatrix-FilterList.txt 
    http://phishing.mailscanner.info/phishing.bad.sites.conf 
    https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt 
    https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt 
    https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt 
    https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt 
    https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt 
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt 
    https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt 
    https://zerodot1.gitlab.io/CoinBlockerLists/list.txt 
    https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt 
    https://zerodot1.gitlab.io/CoinBlockerLists/list_optional.txt 
    https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt 
    https://raw.githubusercontent.com/w13d/adblockListABP-PiHole/master/Spotify.txt 
    https://smokingwheels.github.io/Pi-hole/allhosts

