apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-custom-config
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  05-custom.conf:
{{ toYaml .Values.configData | indent 4 }}
